---
INPUT_DIR: /biology/donaldson/ant_videos
# The framerate to assume if given a .h264 file
h264-framerate: 32
label:
    # Parameters used by the roilabel file
    insignificant-vertices: True        # If true, will draw all vertices
split:
    segment-length: 600     # The duration (in seconds) of each split segment
    min-segment-length: 20  # The minimum length of a split segment to keep

croprot:
    # Parameters used by the croprotate file
    cores: 5        # The number of cores to use for this step
tracks:
    # Parameters used by the ant tracking code (there's a lot of them)
    min-blob: 20                        # The smallest size of blob
                                        # which is interpreted as an ant

    count-warning-threshold: 10         # If more ants than this are seen
                                        # in 5 seconds, throw a warning
                                        # and flag offending tracks.

    num-gaussians: 5                    # The number of Guassians to use  # UPDATE TO 3
                                        # in fitting the background
    num-training-frames: 120            # The number of frames of the
                                        # video to use to identify the
                                        # background

    minimum-background-ratio: 0.70      # The fraction of frames which
                                        # must be matched by the
                                        # background detection
 
    cost-of-nonassignment: 15.0         # The cost of not assigning a
                                        # detection to an existing track.
                                        # Decreasing this makes it more
                                        # likely to assign two ants to
                                        # one track.

    invisible-threshold: 4              # If a newly-detected track is
                                        # missing for this many frames,
                                        # then assume that it was a fake
                                        # track and forget it.
 
    old-age-threshold: 8                # If a track exists for this many
                                        # frames, then it becomes immune
                                        # to the above effect

    visibility-threshold: 0.6           # The minimum fraction of frames
                                        # during an ant's lifetime for
                                        # which it must be visible.

    kalman-initial-error: '200 50'      # The margin of error for the
                                        # Kalman filter, on the initial
                                        # position and velocity

    kalman-motion-noise:  '100 15'      # The amount of variation in
                                        # position and velocity
                                        # which the Kalman filter tolerates

    kalman-measurement-noise: 100.0     # The expected deviation in actual
                                        # measurements

    min-visible-count: 3                # The number of frames for which
                                        # an ant must be spotted for its
                                        # track to be recorded

    min-duration: 1.5                   # The minimum duration for which
                                        # a track must persist to be
                                        # saved as an ant.

    # NEW ARGUMENTS FOR TRACK BEGIN HERE

    # DETECTOR.PY
      # Epsilon Enclosures (62): 0.05



roi-detection:
    # Parameters used by the ROI detection code
    # HSV is the color model used by the code. Information on it can be
    # found here: https://en.wikipedia.org/wiki/HSL_and_HSV
    hsv-hue-tolerance: 25   # How far from pure red the hue can deviate

    hsv-sat-minimum: 55     # The minimum saturation

    hsv-value-minimum: 60   # The minimum value

    smooth-open-size: 1     # The amount by which to "open" the mask
                            # This removes small details.

    smooth-dilate-size: 3   # The amount by which to "dilate" the mask,
                            # expanding detected details.

    smooth-close-size: 3    # The amount by which to "close" the mask,
                            # filling in small holes.

    polygon-epsilon: 0.035  # The amount of wiggle-room in turning
                            # contours into polygons.

    roi-bbox-padding: 2     # The amount of padding around polygons to
                            # include in the ROI.

    force-convex: true      # Force the polygons for each ROI to be convex
...

